version: '3.6'

services:

  node:
    build:
      context: ./services/node
      dockerfile: Dockerfile-dev
    volumes:
      - './services/node:/usr/src/app'
#    ports:
#      - 3001:3001
    environment:
      - ENV=${ENV}
    depends_on:
     - db

  db:
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
#    ports:
#      - 3000:3000
    environment:
      - ENV=${ENV}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - node

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - node
      - client